using Microsoft.EntityFrameworkCore.Migrations;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTrackerAPI.Migrations
{
    /// <inheritdoc />
    public partial class ChangeTransactionAmountToDecimal : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Check if Transactions table exists
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    -- Create table if it doesn't exist
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'Transactions'
                    ) THEN
                        CREATE TABLE ""Transactions"" (
                            ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            ""AccountId"" integer NOT NULL,
                            ""Amount"" numeric NOT NULL,
                            ""Type"" text NOT NULL,
                            ""dateOnly"" date NOT NULL,
                            ""CategoryId"" integer NOT NULL,
                            ""Notes"" text NOT NULL,
                            CONSTRAINT ""PK_Transactions"" PRIMARY KEY (""Id"")
                        );
                    ELSE
                        -- Table exists, alter Amount column from int to decimal if needed
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'Transactions' 
                            AND column_name = 'Amount' 
                            AND data_type = 'integer'
                        ) THEN
                            ALTER TABLE ""Transactions"" ALTER COLUMN ""Amount"" TYPE numeric USING ""Amount""::numeric;
                        END IF;
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Alter Amount column back to integer if table exists
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'Transactions'
                    ) THEN
                        ALTER TABLE ""Transactions"" ALTER COLUMN ""Amount"" TYPE integer USING ""Amount""::integer;
                    END IF;
                END $$;
            ");
        }
    }
}
