# Use the official .NET 8 SDK image for building the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the .csproj file and restore dependencies
COPY ["FinanceTrackerAPI.csproj", "./"]
RUN dotnet restore "FinanceTrackerAPI.csproj"

# Copy the rest of the application files
COPY . .

WORKDIR "/src"
RUN dotnet build "FinanceTrackerAPI.csproj" -c Release -o /app/build

# Publish the app
FROM build AS publish
RUN dotnet publish "FinanceTrackerAPI.csproj" -c Release -o /app/publish

# Use the .NET 8 runtime image as the base for the final image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 5280

# Copy the published app and set the entrypoint
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "FinanceTrackerAPI.dll"]
