# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./*.sln ./
COPY FinanceTrackerAPI/*.csproj ./FinanceTrackerAPI/
COPY FinanceTracker.Data/*.csproj ./FinanceTracker.Data/
COPY FinanceTracker.Domain/*.csproj ./FinanceTracker.Domain/
RUN dotnet restore

# Copy everything else and build
COPY . .
WORKDIR /app/FinanceTrackerAPI
RUN dotnet publish -c Release -o out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/FinanceTrackerAPI/out ./
ENTRYPOINT ["dotnet", "FinanceTrackerAPI.dll"]
